Day4-MVC/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_DAY2.Models
{
    public  class Department
    {
        [Key]
        public int DeptId { get; set; }
    
        public string DeptName { get; set; }

        public virtual ICollection<Student> Students { get; set; } = new HashSet<Student>();
    }
}

Day4-MVC/Models/ErrorViewModel.cs
namespace Day4_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day4-MVC/Models/Student.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_DAY2.Models
{
    public class Student
    {
        
        public int Id { get; set; }
        public string Name { get; set; }
         public string Address { get; set; }
        public int Age { get; set; }

        [ForeignKey(nameof(Department))]
        public int DeptId { get; set; }
        public Department Department { get; set; }
    }
}

Day4-MVC/Controllers/DepartmentController.cs
using Day4_MVC.Context;
using Microsoft.AspNetCore.Mvc;
using MVC_DAY2.Models;

namespace Day4_MVC.Controllers
{
    public class DepartmentController : Controller
    {
        MyContext db = new MyContext();

        [HttpGet]
        public IActionResult Index()
        {
            var departments = db.Departments;

            return View(departments);
        }
        public IActionResult Details(int id)
        {
            var department = db.Departments.Find(id);
            if (department == null)
            {
                return RedirectToAction("Index");
            }
            return View(department);
        }
     
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        public IActionResult Create(Department department)
        {
            db.Departments.Add(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
      
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var dept = db.Departments.Find(id);
            if (dept == null)
            {
                return RedirectToAction("Index");
            }
            return View(dept);
        }
       
        
        [HttpPost]
        public IActionResult Edit(Department department)
        {
            
            var dept = db.Departments.Find(department.DeptId);
            if (dept == null)
            {
                return RedirectToAction("Index");
            }
            dept.DeptName = department.DeptName;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
       
        public IActionResult Delete(int id)
        {
            var dept = db.Departments.Find(id);
            if (dept == null)
            {
                return RedirectToAction("Index");
            }
            db.Departments.Remove(dept);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Day4-MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Day4_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Day4_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day4-MVC/Controllers/StudentController.cs
using Day4_MVC.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_DAY2.Models;

namespace Day4_MVC.Controllers
{
    public class StudentController : Controller
    {
        MyContext db = new MyContext();

        [HttpGet]
        public IActionResult Index()
        {
            var students = db.Students.Include(e => e.Department);

            return View(students);
        }
        public IActionResult Details(int id)
        {
            var students = db.Students.Include(e => e.Department).FirstOrDefault(e => e.Id == id);
            if (students == null)
            {
                return RedirectToAction("Index");
            }
            return View(students);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag._Depts = new SelectList(db.Departments, "DeptId", "DeptName");
            return View();
        }
       
        [HttpPost]
        public IActionResult Create(Student student)
        {
            db.Students.Add(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var students = db.Students.Include(e => e.Department).FirstOrDefault(e => e.Id == id);
            if (students == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag._Depts = new SelectList(db.Departments, "DeptId", "DeptName");
            return View(students);
        }
      
        [HttpPost]
        public IActionResult Edit(Student students)
        {
            var oldstudent = db.Students.Find(students.Id);
            if (oldstudent == null)
            {
                return RedirectToAction("Index");
            }
            oldstudent.Name = students.Name;
            oldstudent.Age = students.Age;
            oldstudent.Address = students.Address;
            oldstudent.DeptId = students.DeptId;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var students = db.Students.Find(id);
            if (students == null)
            {
                return RedirectToAction("Index");
            }
            db.Students.Remove(students);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Day4-MVC/Views/Department/Create.cshtml
@model MVC_DAY2.Models.Department
<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Add New Department</h2>
</div>

<br />
<hr />
<br />

<form action="~/Department/Create" method="post">

    <div class="form-group">
        <label for="DeptName" class="form-label">Department Name</label>
        <input type="text" name="DeptName" class="form-control" />
    </div>

    <div class="d-flex justify-content-center gap-3 my-5">
        <input type="submit" value="Create Department" class="btn btn-success" />
        <a href="~/Department/Index" class="btn btn-secondary">Cancel</a>
    </div>

</form>

Day4-MVC/Views/Department/Details.cshtml
@using MVC_DAY2.Models
@model Department

<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Department Details</h2>
</div>

<br />
<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Department Name: @Model.DeptName</h5>
            <h6 class="card-subtitle mb-2 text-muted">Department Id: @Model.DeptId</h6>
            <div class="d-flex justify-content-center mt-3">
                <a href="~/Department/Index" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</div>

Day4-MVC/Views/Department/Edit.cshtml
@model MVC_DAY2.Models.Department

<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Edit Department</h2>
</div>

<br />
<hr />
<br />

<form action="~/Department/Edit" method="post">

    @* <div class="form-group">
        <label for="DeptId" class="form-label">Department Id</label>
        <input type="number" name="DeptId" class="form-control" value="@Model.DeptId" disabled/>
    </div> *@

    <div class="form-group">
        <input type="number" name="DeptId" class="form-control" value="@Model.DeptId" hidden />
    </div>

    <div class="form-group">
        <label for="DeptName" class="form-label">Department Name</label>
        <input type="text" name="DeptName" class="form-control" value="@Model.DeptName" />
    </div>

    <div class="d-flex justify-content-center gap-3 my-5">
        <input type="submit" value="Edit Department" class="btn btn-success" />
        <a href="~/Department/Index" class="btn btn-secondary">Cancel</a>
    </div>

</form>

Day4-MVC/Views/Department/Index.cshtml
@using MVC_DAY2.Models

@model IEnumerable<Department>



<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Departments Portal</h2>
</div>

<br />
<hr />
<br />

<table class="table text-center">
    <thead>
        <tr>
            <th scope="col">Department Id</th>
            <th scope="col">Department Name</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.DeptId</th>
                <td scope="row">@item.DeptName</td>
                <td>
                    <a href="~/Department/Details/@item.DeptId" class="btn btn-primary mx-2">View</a>
                    <a href="~/Department/Edit/@item.DeptId" class="btn btn-secondary mx-2">Edit</a>
                    <a href="~/Department/Delete/@item.DeptId" class="btn btn-danger mx-2">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <a href="~/Department/Create" class="btn btn-success">Add Department</a>
    </tfoot>
</table>

Day4-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome TO MVC LAB 3  </h1>
   
</div>

Day4-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day4_MVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day4_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Day4_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Day4_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Day4-MVC/Views/Student/Create.cshtml
@using MVC_DAY2.Models
@model Student

<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Add New Student</h2>
</div>

<br />
<hr />
<br />

<form action="~/Student/Create" method="post">

    <div class="form-group">
        <label for="Name" class="form-label">Student Name</label>
        <input type="text" name="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Age" class="form-label">Student Age</label>
        <input type="text" name="Age" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Address" class="form-label">Student Address</label>
        <input type="text" name="Address" class="form-control" />
    </div>


    <div class="form-group">
        <label for="DeptId" class="form-label">Department</label>
        <select name="DeptId" class="form-control">
            @foreach (var item in ViewBag._depts)
            {
                <option value="@item.Value">@item.Text</option>
            }
        </select>
    </div>


    <div class="d-flex justify-content-center gap-3 my-5">
        <input type="submit" value="Create Student" class="btn btn-success" />
        <a href="~/Student/Index" class="btn btn-secondary">Cancel</a>
    </div>

</form>

Day4-MVC/Views/Student/Details.cshtml
@using MVC_DAY2.Models
@model Student

<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Department Details</h2>
</div>

<br />
<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Student Name: @Model.Name</h5>
            <h6 class="card-subtitle mb-2 text-muted">Student Id: @Model.Id</h6>
            <h6 class="card-subtitle mb-2 text-muted">Student Age: @Model.Age</h6>
            <h6 class="card-subtitle mb-2 text-muted">Student Address: @Model.Address</h6>
            <h6 class="card-subtitle mb-2 text-muted">Department: @Model.Department.DeptName</h6>
            <div class="d-flex justify-content-center mt-3">
                <a href="~/Student/Index" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</div>

Day4-MVC/Views/Student/Edit.cshtml
@using MVC_DAY2.Models
@model Student

<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Edit Student</h2>
</div>

<br />
<hr />
<br />

<form action="~/Student/Edit" method="post">

    <div class="form-group">
        <input type="number" name="Id" class="form-control" value="@Model.Id" hidden />
    </div>

    <div class="form-group">
        <label for="Name" class="form-label">Student Name</label>
        <input type="text" name="Name" class="form-control" value="@Model.Name" />
    </div>

    <div class="form-group">
        <label for="Age" class="form-label">Student Age</label>
        <input type="text" name="Age" class="form-control" value="@Model.Age" />
    </div>

    <div class="form-group">
        <label for="Address" class="form-label">Student Address</label>
        <input type="text" name="Address" class="form-control" value="@Model.Address" />
    </div>


    <div class="form-group">
        <label for="DeptId" class="form-label">Department</label>
        <select name="DeptId" class="form-control">
            <option value="@Model.DeptId">@Model.Department.DeptName</option>
            @foreach (var item in ViewBag._depts)
            {
                <option value="@item.Value">@item.Text</option>
            }
        </select>
    </div>

    <div class="d-flex justify-content-center gap-3 my-5">
        <input type="submit" value="Edit Student" class="btn btn-success" />
        <a href="~/Department/Index" class="btn btn-secondary">Cancel</a>
    </div>

</form>

Day4-MVC/Views/Student/Index.cshtml
@using MVC_DAY2.Models
@model IEnumerable<Student>

<br />

<div class="d-flex justify-content-center">
    <h2 class="text-success">Student Portal</h2>
</div>

<br />
<hr />
<br />

<table class="table text-center">
    <thead>
        <tr>
            <th scope="col">Student Id</th>
            <th scope="col">Student Name</th>
            <th scope="col">Student Age</th>
            <th scope="col">Student Address</th>
            <th scope="col">Department</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td scope="row">@item.Name</td>
                <td scope="row">@item.Age</td>
                <td scope="row">@item.Address</td>
                <td scope="row">@item.Department.DeptName</td>
                <td>
                    <a href="~/Student/Details/@item.Id" class="btn btn-primary mx-2">View</a>
                    <a href="~/Student/Edit/@item.Id" class="btn btn-secondary mx-2">Edit</a>
                    <a href="~/Student/Delete/@item.Id" class="btn btn-danger mx-2">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <a href="~/Student/Create" class="btn btn-success">Add Student</a>
    </tfoot>
</table>